/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'adminbrad' at '03/09/16 4:17 PM' with Gradle 2.14
 *
 * @author adminbrad, @date 03/09/16 4:17 PM
 */
import java.io.*;
import javax.servlet.*;
import javax.servlet.http.*;

public class index extends HttpServlet {
 
  private String PageName="Main Index Page";

  public void init() throws ServletException
  {
      // Do required initialization
      
  }

  public void doGet(HttpServletRequest request,
                    HttpServletResponse response)
            throws ServletException, IOException
  {
	  /*
	   * This is the main index page doGet "code behind" It must end by redirecting to the 
	   * actual JSP page which is based on the page name, 
	   */
	  String uri = request.getRequestURI();
	  String pageName = uri.substring(uri.lastIndexOf("/")+1);
	  pageName = pageName.substring(0, pageName.indexOf('.'));
	  RequestDispatcher dispatcher = null;
      try {			  
    	  //don't forget to set any attributes
    	  request.setAttribute("PageName", PageName );           
    	  dispatcher = request.getRequestDispatcher("/WEB-INF/jsp/" + pageName + ".jsp");
    	
	  
      }
      catch (Exception e)
      {
    	  
      }
      if(dispatcher != null){
          dispatcher.forward(request,response);
      }
      else
      {
    	  response.sendError(HttpServletResponse.SC_NOT_FOUND);
      }
  }
  
  public void destroy()
  {
      // do nothing.
  }
}